const todosOsEventos = [
  {
    resposta: "independência do brasil",
    respostasAceitas: [
      "independência do brasil",
      "proclamação da independência",
      "independencia brasil",
      "emancipação do brasil",
    ],
    dicas: [
      "Um grito à beira de um rio, em 1822, marcou a separação de uma colônia de sua metrópole.",
      "O protagonista principal era o filho do rei que havia retornado para a Europa.",
      "O ato foi uma resposta às exigências de recolonização por parte das Cortes Portuguesas.",
      "O Príncipe Regente proclamou a autonomia política da nação, tornando-se seu primeiro imperador.",
      "Dom Pedro I, às margens do riacho Ipiranga, disse: 'Independência ou Morte!'.",
    ],
    dificuldade: "Fácil",
  },
  {
    resposta: "queda do muro de berlim",
    respostasAceitas: [
      "queda do muro de berlim",
      "fim do muro de berlim",
      "reunificação da alemanha",
      "demolição do muro de berlim",
    ],
    dicas: [
      "Aconteceu no final do século XX.",
      "Relacionada ao fim da Guerra Fria.",
      "Dividia uma cidade alemã.",
      "Aconteceu em 1989.",
      "Representa a reunificação da Alemanha.",
    ],
    dificuldade: "Médio",
  },
  {
    resposta: "proclamação da república",
    respostasAceitas: [
      "proclamação da república",
      "queda da monarquia",
      "início da república no brasil",
      "deposição de dom pedro II",
    ],
    dicas: [
      "Um antigo império na América do Sul viu seu fim em um dia de outono.",
      "O governante que partiu havia reinado por quase 50 anos e era filho de um 'Libertador'.",
      "Militares e republicanos, insatisfeitos com a escravidão e o regime, foram os principais agentes da mudança.",
      "O evento transformou o sistema de governo do país, substituindo a monarquia por um novo regime.",
      "O Marechal Deodoro da Fonseca liderou o movimento, tornando-se o primeiro presidente provisório.",
    ],
    dificuldade: "Fácil",
  },
  {
    resposta: "revolução francesa",
    respostasAceitas: [
      "revolução francesa",
      "queda da bastilha",
      "fim da monarquia francesa",
      "rebelião popular na frança",
    ],
    dicas: [
      "Teve início em 1789.",
      "Foi marcada pelo lema 'Liberdade, Igualdade e Fraternidade'.",
      "Ocorreu contra os privilégios da nobreza e do clero.",
      "Mudou profundamente a estrutura social da França.",
      "Terminou com a ascensão de Napoleão Bonaparte.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "descobrimento da américa",
    respostasAceitas: [
      "descobrimento da américa",
      "chegada de colombo à américa",
      "cristóvão colombo descobriu a américa",
      "exploração do novo mundo",
    ],
    dicas: [
      "Um navegador genovês, a serviço de um reino ibérico, buscou uma nova rota para o Oriente e encontrou um novo continente.",
      "Suas caravelas, a Niña, Pinta e Santa María, aportaram em ilhas caribenhas em 1492.",
      "O evento abriu caminho para a colonização europeia de vastas terras habitadas por povos nativos.",
      "Ele acreditava ter chegado às Índias, mas na verdade encontrou um 'Novo Mundo'.",
      "Cristóvão Colombo chegou ao continente americano.",
    ],
    dificuldade: "Médio",
  },
  {
    resposta: "descobrimento do brasil",
    respostasAceitas: [
      "descobrimento do brasil",
      "chegada dos portugueses ao brasil",
      "início da colonização do brasil",
      "achamento do brasil",
    ],
    dicas: [
      "Navegadores europeus, buscando novas rotas para as Índias, chegaram a uma nova terra em 1500.",
      "A frota que aportou era composta por navios de um reino da Península Ibérica.",
      "Os primeiros habitantes encontrados eram povos originários, que viviam aqui há milênios.",
      "O comandante da expedição enviou uma carta ao seu rei, descrevendo a 'Terra de Vera Cruz'.",
      "Pedro Álvares Cabral chegou à costa do que hoje conhecemos como Brasil.",
    ],
    dificuldade: "Fácil",
  },
  {
    resposta: "queda de constantinopla",
    respostasAceitas: [
      "queda de constantinopla",
      "fim do império bizantino",
      "fim da idade média",
      "conquista de constantinopla",
    ],
    dicas: [
      "Uma importante cidade, ponte entre dois continentes, foi conquistada em 1453.",
      "Sua queda marcou o fim de um império milenar no Leste Europeu.",
      "Canhões gigantes foram usados no cerco, mudando a arte da guerra.",
      "A cidade era a capital do Império Bizantino.",
      "Foi tomada pelos turcos otomanos, liderados por Maomé II, e se tornou Istambul.",
    ],
    dificuldade: "Médio",
  },
  {
    resposta: "reforma protestante",
    respostasAceitas: [
      "reforma protestante",
      "reforma religiosa",
      "movimento de reforma",
      "reforma luterana",
    ],
    dicas: [
      "Um movimento religioso que abalou a Europa no século XVI, contestando dogmas e práticas da Igreja.",
      "Começou com a afixação de 95 teses em uma porta de igreja.",
      "A invenção da prensa de tipos móveis foi fundamental para sua disseminação.",
      "Um monge alemão foi a figura central desse questionamento.",
      "Martin Lutero e a venda de indulgências foram o estopim.",
    ],
    dificuldade: "Médio",
  },
  {
    resposta: "revolução americana",
    respostasAceitas: [
      "revolução americana",
      "guerra da independência dos estados unidos",
      "guerra da independência dos EUA",
      "revolta das treze colônias",
      "revolta das 13 colônias",
      "independência americana",
    ],
    dicas: [
      "Um grupo de colônias na América do Norte lutou por sua liberdade contra uma poderosa metrópole europeia.",
      "A frase 'Sem tributação sem representação' resumia o sentimento de insatisfação.",
      "Resultou na criação de um dos países mais influentes do mundo moderno.",
      "O conflito levou à Declaração de Independência em 1776.",
      "As Treze Colônias se libertaram do domínio britânico e formaram os Estados Unidos.",
    ],
    dificuldade: "Médio",
  },
  {
    resposta: "fim da escravidão no brasil",
    respostasAceitas: [
      "fim da escravidão no brasil",
      "abolição da escravatura no brasil",
      "lei áurea",
      "abolição da escravidão",
    ],
    dicas: [
      "Um importante ato legal, assinado em 13 de maio, libertou uma grande parcela da população brasileira.",
      "Apesar de não resolver todos os problemas, foi um marco na luta por direitos humanos.",
      "A princesa que o assinou governava interinamente na ausência de seu pai.",
      "A lei de 1888 aboliu de vez o trabalho forçado de pessoas africanas e seus descendentes.",
      "A Princesa Isabel assinou a uma lei, libertando os escravos.",
    ],
    dificuldade: "Fácil",
  },
  {
    resposta: "invenção da imprensa",
    respostasAceitas: [
      "invenção da imprensa",
      "criação da imprensa de gutenberg",
      "início da imprensa tipográfica",
      "nascimento da imprensa moderna",
    ],
    dicas: [
      "Uma tecnologia que revolucionou a disseminação do conhecimento e da informação no século XV.",
      "Permitiu a produção em massa de livros, antes copiados à mão.",
      "A primeira obra impressa em grande escala foi a Bíblia.",
      "Um inventor alemão é amplamente creditado por seu desenvolvimento na Europa.",
      "Johannes Gutenberg e seus tipos móveis foram a chave para essa inovação.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "construção da muralha da china",
    respostasAceitas: [
      "construção da muralha da china",
      "edificação da muralha da china",
      "levantamento da grande muralha",
      "erguimento da muralha chinesa",
    ],
    dicas: [
      "Uma gigantesca estrutura defensiva, visível até do espaço (com ressalvas!), foi erguida por uma antiga civilização asiática.",
      "Seu principal objetivo era proteger o império de invasões nômades vindas do norte.",
      "Sua construção durou séculos, com diferentes dinastias contribuindo para sua extensão.",
      "Soldados e camponeses foram forçados a trabalhar nesse projeto monumental, muitas vezes sob condições brutais.",
      "Qin Shi Huang é frequentemente associado ao início da unificação e expansão dessa fortificação.",
    ],
    dificuldade: "Médio",
  },
  {
    resposta: "construção das pirâmides de gizé",
    respostasAceitas: [
      "construção das pirâmides de gizé",
      "edificação das pirâmides do egito",
      "levantamento das pirâmides de gizé",
      "construção das grandes pirâmides egípcias",
    ],
    dicas: [
      "Monumentais estruturas de pedra, erguidas há milênios, dominam a paisagem de um deserto no nordeste da África.",
      "Eram tumbas grandiosas, construídas para abrigar os restos mortais de governantes divinizados.",
      "A maior delas, e uma das Sete Maravilhas do Mundo Antigo, é a de Quéops.",
      "Foram edificadas por uma civilização antiga que se desenvolveu às margens do rio Nilo.",
      "Representam a engenhosidade do Antigo Egito e serviam de morada eterna para seus faraós.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "revolução industrial",
    respostasAceitas: [
      "revolução industrial",
      "início da era industrial",
      "transformação industrial",
      "processo de industrialização",
    ],
    dicas: [
      "Um período de profundas transformações econômicas e sociais que se iniciou no século XVIII.",
      "Levou à invenção de máquinas que mudaram a forma de produção, saindo do manual para o mecanizado.",
      "O uso do vapor como força motriz e o carvão como combustível foram cruciais.",
      "Transformou a Inglaterra de uma sociedade agrária em uma sociedade predominantemente urbana e fabril.",
      "A máquina a vapor e a produção têxtil em larga escala são símbolos desse período de grandes inovações.",
    ],
    dificuldade: "Médio",
  },
  {
    resposta: "grande depressão",
    respostasAceitas: [
      "grande depressão",
      "crise de 1929",
      "colapso econômico mundial",
      "quebra da bolsa de nova york",
      "crise de 29",
    ],
    dicas: [
      "Uma grave crise econômica global que teve início na década de 1920 e durou boa parte da década de 1930.",
      "O 'crash'de uma importante bolsa de valores foi o estopim inicial.",
      "Milhões de pessoas perderam seus empregos e suas economias, com desemprego massivo e pobreza.",
      "Atingiu seu auge após a 'Terça-feira Negra' de 1929.",
      "O colapso da Bolsa de Nova York (Wall Street) marcou o início dessa recessão mundial.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "guerra fria",
    respostasAceitas: [
      "guerra fria",
      "início da guerra fria",
      "começo da guerra fria",
      "surgimento da guerra fria",
      "início do conflito leste-oeste",
      "início da rivalidade EUA e URSS",
    ],
    dicas: [
      "Um período de intensa rivalidade geopolítica, sem conflito armado direto, entre duas superpotências após a Segunda Guerra Mundial.",
      "O mundo foi dividido em blocos ideológicos: capitalismo versus socialismo.",
      "A Corrida Armamentista e a Corrida Espacial foram manifestações dessa disputa.",
      "Teve como protagonistas os Estados Unidos e a União Soviética.",
      "O Muro de Berlim se tornou um símbolo dessa divisão ideológica entre EUA e URSS.",
    ],
    dificuldade: "Fácil",
  },
  {
    resposta: "construção do canal do panamá",
    respostasAceitas: [
      "construção do canal do panamá",
      "obra do canal do panamá",
      "construção do canal interoceânico do panamá",
      "construção da passagem do Panamá",
    ],
    dicas: [
      "Uma monumental obra de engenharia que conecta dois grandes oceanos, encurtando rotas marítimas.",
      "Sua construção enfrentou desafios como doenças tropicais e o relevo montanhoso.",
      "Os Estados Unidos desempenharam um papel crucial em sua finalização e controle por décadas.",
      "Permite que navios passem do Atlântico para o Pacífico sem contornar a América do Sul.",
      "Essa via aquática artificial atravessa o istmo do Panamá.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "peste negra",
    respostasAceitas: [
      "peste negra",
      "peste bubônica",
      "peste medieval",
      "pandemia da peste",
    ],
    dicas: [
      "Uma pandemia devastadora que assolou a Europa, Ásia e África no século XIV.",
      "Causou a morte de milhões de pessoas, reduzindo drasticamente a população.",
      "Era transmitida por pulgas em ratos e se manifestava com inchaços escuros.",
      "É considerada uma das mais mortais da história da humanidade.",
      "A doença bubônica dizimou cerca de um terço da população europeia.",
    ],
    dificuldade: "Fácil",
  },
  {
    resposta: "unificação alemã",
    respostasAceitas: [
      "unificação alemã",
      "unificação da alemanha",
      "formação do império alemão",
      "fundação do segundo reich",
    ],
    dicas: [
      "Um processo político do século XIX que reuniu vários estados independentes em um único país.",
      "A Prússia foi a força motriz por trás desse processo, com um famoso chanceler à frente.",
      "Envolveu guerras contra a Dinamarca, Áustria e França para consolidar o novo Estado.",
      "Resultou na criação de um novo império poderoso no centro da Europa.",
      "Otto von Bismarck foi o arquiteto da formação do Império Alemão em 1871.",
    ],
    dificuldade: "Médio",
  },
  {
    resposta: "era vargas",
    respostasAceitas: [
      "era vargas",
      "governo de getúlio vargas",
      "período vargas na presidência",
      "regime vargas",
    ],
    dicas: [
      "Um longo período da história brasileira, de 1930 a 1945 e depois de 1951 a 1954, marcado por forte centralização do poder.",
      "Incluiu um período de ditadura conhecido como Estado Novo.",
      "Promoveu leis trabalhistas e o desenvolvimento industrial do país.",
      "O líder desse período governou por 15 anos seguidos, com um estilo populista.",
      "Getúlio Vargas dominou a política brasileira por décadas, implementando grandes mudanças sociais e econômicas.",
    ],
    dificuldade: "Médio",
  },
  {
    resposta: "colapso da união soviética",
    respostasAceitas: [
      "colapso da união soviética",
      "queda da união soviética",
      "dissolução da URSS",
      "fim da união soviética",
      "queda da URSS",
      "fim da URSS",
      "dissolação da união soviética",
    ],
    dicas: [
      "O fim de um vasto império socialista no Leste Europeu e Ásia Central, no final do século XX.",
      "A política de 'Glasnost' e 'Perestroika' tentou reformar o sistema, mas acabou acelerando o desmantelamento.",
      "Sua desintegração levou à formação de vários novos países independentes.",
      "Em 1991, esse bloco político e econômico se desfez, encerrando a Guerra Fria.",
      "Mikhail Gorbachev presidiu os últimos anos da URSS, que se fragmentou em 15 repúblicas.",
    ],
    dificuldade: "Médio",
  },
  {
    resposta: "revolução francesa",
    respostasAceitas: [
      "revolução francesa",
      "revolta francesa",
      "transformação francesa",
      "rebelião na frança",
    ],
    dicas: [
      "Uma nação europeia buscou drasticamente liberdade, igualdade e fraternidade no final do século XVIII.",
      "O descontentamento com a monarquia absolutista e a sociedade estamental atingiu seu ponto de ebulição.",
      "A Tomada da Bastilha é um marco simbólico do início desse turbilhão social e político.",
      "Acabou com privilégios da nobreza e do clero, levando à execução de um rei e uma rainha.",
      "Inspirou movimentos por todo o mundo e deu origem à Declaração dos Direitos do Homem e do Cidadão.",
    ],
    dificuldade: "Médio",
  },
  {
    resposta: "inconfidência mineira",
    respostasAceitas: [
      "inconfidência mineira",
      "conjuração mineira",
      "revolução de 1789",
      "revolta de vila rica",
    ],
    dicas: [
      "Um movimento de caráter separatista ocorreu no Brasil colonial, no final do século XVIII, por causa de impostos.",
      "Os revoltosos buscavam a independência de sua capitania em relação à coroa portuguesa.",
      "A Coroa impunha a 'derrama', uma cobrança forçada de ouro que gerava grande descontentamento.",
      "Um de seus líderes, um alferes, foi julgado e executado por traição, tornando-se mártir.",
      "O grupo, que incluía poetas e intelectuais, foi traído, e o principal executado foi Tiradentes.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "incidente de tunguska",
    respostasAceitas: [
      "incidente de tunguska",
      "impacto de tunguska",
      "queda de tunguska",
      "acidente de tunguska",
      "fenômeno de tunguska",
    ],
    dicas: [
      "Um evento misterioso que ocorreu em 1908 em uma região remota da Sibéria, sem cratera de impacto.",
      "Provocou uma explosão equivalente a milhares de bombas atômicas, achatando milhões de árvores.",
      "Cientistas especulam que foi causado por um meteoro ou cometa que se desintegrou na atmosfera.",
      "Não houve mortes humanas registradas diretamente, mas a floresta foi devastada em uma área de 2.000 km².",
      "A enorme explosão aérea sobre a Bacia do Rio Podkamennaya Tunguska permanece um enigma científico.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "guerra do emu",
    respostasAceitas: [
      "guerra do emu",
      "campanha contra os emus",
      "conflito com os emus",
      "guerra com os emus",
      "ação militar contra os emus",
    ],
    dicas: [
      "Um inusitado conflito militar ocorrido na Austrália em 1932.",
      "O objetivo da operação era controlar uma superpopulação de grandes aves nativas.",
      "Veteranos de guerra com metralhadoras foram enviados para a batalha.",
      "Os 'inimigos' eram aves grandes e velozes, que estavam destruindo plantações.",
      "Foi um fracasso militar, onde o Exército Australiano tentou, sem sucesso, erradicar emus.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "saque de roma",
    respostasAceitas: [
      "saque de roma",
      "razia de roma",
      "escaramuça em roma",
      "ataque a roma",
      "queda de roma",
    ],
    dicas: [
      "Uma cidade imperial, outrora inexpugnável, foi invadida e pilhada por uma tribo germânica.",
      "O evento chocou o mundo romano, simbolizando a fragilidade do Império do Ocidente.",
      "Apesar da pilhagem, os invasores respeitaram os templos e igrejas.",
      "O rei visigodo Alarico liderou suas tropas na invasão da cidade eterna.",
      "A capital do Império Romano do Ocidente foi saqueada pelos Visigodos.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "revolta da vacina",
    respostasAceitas: [
      "revolta da vacina",
      "revolta sanitária",
      "vacinação compulsória",
      "obrigatoriedade da vacina",
      "protesto contra a vacinação",
    ],
    dicas: [
      "Uma revolta popular que ocorreu na capital do Brasil no início do século XX.",
      "Foi uma reação à obrigatoriedade de uma medida sanitária imposta pelo governo.",
      "A cidade passava por uma reforma urbana e sanitária, com demolições de cortiços.",
      "O sanitarista Oswaldo Cruz liderava a campanha que gerou a insatisfação.",
      "Ocorreu no Rio de Janeiro em 1904, como protesto contra a vacinação obrigatória contra a varíola.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "dieta de worms",
    respostasAceitas: [
      "dieta de worms",
      "dieta imperial",
      "assembleia de worms",
      "dieta imperial de worms",
    ],
    dicas: [
      "Uma assembleia imperial crucial realizada em 1521, que confrontou um reformador religioso.",
      "O imperador do Sacro Império Romano-Germânico presidia o encontro.",
      "O religioso foi convocado para retratar suas ideias, mas se recusou a fazê-lo, a menos que fosse convencido pelas escrituras.",
      "O evento marcou um ponto de virada na Reforma Protestante, confirmando a excomunhão de seu principal líder.",
      "Foi onde Martinho Lutero se recusou a se retratar diante do Imperador Carlos V, dizendo: 'Aqui eu permaneço'.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "grande cisma do ocidente",
    respostasAceitas: [
      "grande cisma do ocidente",
      "cisma papal",
      "cisma do ocidente",
      "grande cisma",
    ],
    dicas: [
      "Um período de crise na Igreja Católica que durou quase 40 anos, do final do século XIV ao início do XV.",
      "Houve simultaneamente dois, e por um tempo até três, papas reivindicando a autoridade máxima.",
      "As divisões eram geográficas e políticas, com reinos europeus apoiando diferentes 'papas'.",
      "A resolução veio com o Concílio de Constança, que elegeu um novo e único papa.",
      "A Igreja Católica se viu dividida, com sedes papais em Roma e Avignon.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "cerco de leningrado",
    respostasAceitas: [
      "cerco de leningrado",
      "batalha de leningrado",
      "cerco de são petersburgo",
      "bloqueio de leningrado",
    ],
    dicas: [
      "Um dos cercos mais longos e brutais da história, ocorrido durante a Segunda Guerra Mundial.",
      "A cidade, de importância estratégica, resistiu por quase 900 dias.",
      "Milhões de civis morreram de fome, frio e bombardeios durante o bloqueio.",
      "Foi uma tentativa da Alemanha Nazista de aniquilar a população de uma grande cidade soviética.",
      "A cidade de São Petersburgo (então Leningrado) foi sitiada pelas forças alemãs por quase três anos.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "guerra dos cem anos",
    respostasAceitas: [
      "guerra dos cem anos",
      "guerra dos 100 anos",
      "guerra eduardiana",
      "guerra carolíngia",
      "conflito franco-inglês",
      "períodos da guerra dos cem anos",
    ],
    dicas: [
      "Uma série de conflitos intermitentes que duraram bem mais do que um século, na Idade Média.",
      "Disputas territoriais e sucessórias pelo trono de um reino foram as principais causas.",
      "A participação de uma jovem camponesa que se tornou heroína marcou um dos períodos.",
      "Envolveu principalmente as coroas da Inglaterra e da França.",
      "O longo conflito entre ingleses e franceses, com a figura de Joana d'Arc.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "guerra da coreia",
    respostasAceitas: [
      "guerra da coreia",
      "conflito coreano",
      "guerra coreana",
    ],
    dicas: [
      "Um conflito armado que dividiu uma península asiática em duas nações.",
      "Envolveu o apoio de grandes potências mundiais a lados opostos.",
      "Aconteceu na década de 1950.",
      "Teve como resultado a divisão da Coreia em Norte e Sul.",
      "Começou com a invasão da Coreia do Sul pela Coreia do Norte.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "revolução cubana",
    respostasAceitas: [
      "revolução cubana",
      "movimento 26 de julho",
      "golpe de estado em cuba",
      "luta armada em cuba",
      "castrismo",
    ],
    dicas: [
      "Um movimento que derrubou um governo ditatorial em uma ilha caribenha.",
      "Teve como líder um famoso guerrilheiro que se tornou presidente.",
      "Levou ao estabelecimento de um regime socialista próximo aos Estados Unidos.",
      "Ocorreu na década de 1950.",
      "Fidel Castro liderou a revolução que derrubou Fulgencio Batista.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "guerra do vietnã",
    respostasAceitas: [
      "guerra do vietnã",
      "guerra vietnamita",
      "guerra americana",
      "vietnamização",
      "segunda guerra da indochina",
    ],
    dicas: [
      "Um longo e sangrento conflito no sudeste asiático que envolveu os Estados Unidos.",
      "Teve como pano de fundo a Guerra Fria.",
      "Causou grande divisão na sociedade americana.",
      "Terminou com a retirada das forças americanas e a unificação do país.",
      "Ocorreu entre as décadas de 1950 e 1970.",
    ],
    dificuldade: "Difícil",
  },
  {
    resposta: "invenção da lâmpada elétrica",
    respostasAceitas: [
      "invenção da lâmpada elétrica",
      "invenção da lâmpada",
      "lâmpada de edison",
      "descoberta da lâmpada elétrica",
      "criação da lâmpada incandescente",
    ],
    dicas: [
      "Uma inovação que trouxe a luz para dentro das casas e cidades, transformando as noites.",
      "Substituiu velas e lampiões a gás como principal fonte de iluminação.",
      "Um inventor americano é amplamente conhecido por aperfeiçoar e comercializar essa tecnologia.",
      "Tornou possível trabalhar e se divertir após o pôr do sol de forma mais eficiente.",
      "Thomas Edison é o nome mais associado à criação da lâmpada incandescente prática.",
    ],
    dificuldade: "Fácil",
  },
  {
    resposta: "construção da torre eiffel",
    respostasAceitas: [
      "construção da torre eiffel",
      "edificação da torre eiffel",
      "construção do monumento parisiense",
      "realização da torre eiffel",
      "obra da torre eiffel",
      "torre eiffel",
    ],
    dicas: [
      "Uma estrutura icônica de ferro, construída para um grande evento mundial no final do século XIX.",
      "Localiza-se em uma das cidades mais famosas da Europa.",
      "Foi o edifício mais alto do mundo por mais de 40 anos após sua construção.",
      "Erguida para a Exposição Universal de 1889.",
      "É o símbolo mais famoso de Paris, na França.",
    ],
    dificuldade: "Fácil",
  },
];
